### ISSUE TITLE
주문 생성

### ISSUE THREAD

**Issue by jungbin97** [je-pa/ecommerce#16]

**Comment by jungbin97** [comment]
안녕하세요. 구경하다가 버튼을 잘못눌러 하위이슈가 생성되어 버렸습니다. 죄송합니다...! 혹시 발견하시면 삭제 부탁드리겠습니다!!

**Comment by je-pa** [comment]
안녕하세요. 저 정말 궁금해서 그런데 혹시 어떻게 여기 오시게 되셨나요? 정말 궁금해서요!

**Comment by jungbin97** [comment]
@je-pa 네 안녕하세요! Spring Cloud로 MSA 프로젝트 진행중인데요 관련해서 검색해보다 이슈관리 잘되어있어서 구경하다가 잘못 눌렀습니다..>!!
